const vec3 RED = vec3(1.0, .349, .369);
const vec3 YELLOW = vec3(1.0, .792, .227);
const vec3 GREEN = vec3(.501, .788, .149);
const vec3 BLUE = vec3(.098, .470, .769);
const vec3 PURPLE = vec3(.416, .298, .576);
const vec3 BLACK = vec3(.0, .0, .0);
const vec3 WHITE = vec3(1., 1., 1.);

const vec3 YELLOW_WHITE = mix(WHITE, YELLOW, .3);

const vec3 MONOLITH_BLACK = mix(BLACK, PURPLE, .1);

const float FUZZ = .007;